### ISSUE TITLE
Configurar o AppDbContext como um DbContext EntityFramework para conexão com banco de dados postgreSQL

### ISSUE THREAD

**Issue by danielpinheiro2** [jramso/AgendamentoBanhoETosa#3]
## Use a documentação como modelo

[Link NPGSQL EntityFrameWork](https://www.npgsql.org/efcore/?tabs=context-pooling)

**Comment by jramso** [comment]
AppDbcontext estruturado falta fazer o vinculo de chaves estrangeiras entre as classes
